MyWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url('admin/', admin.site.urls),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^new_simulation/$", views.SimulationPage.as_view(), name="simulation"),
    #url(r"^new_simulation/$", views.post_new, name='post_new'),
    url(r"^result/$", views.ResultPage.as_view(), name="result"),
    ]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

Main/models.py
from django.db import models

# Create your models here.

MyWeb/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse



class Numsum(models.Model):
    #author = models.ForeignKey('auth.User', 'on_delete')
    num1 = models.IntegerField(blank=True, null=True)
    num2 = models.IntegerField(blank=True, null=True)
    num3 = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.num1, self.num2

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone


class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)

MyWeb/forms.py
from django import forms

from .models import Numsum


class PostForm(forms.Form):
    Number_of_Costomers = forms.IntegerField()
    Number_of_Receptionists = forms.IntegerField()
    Min_serving_time_of_the_receptionits = forms.IntegerField()
    Max_serving_time_of_the_receptionits = forms.IntegerField()
    MinCustonArrivalTime = forms.IntegerField()
    MaxCustonArrivalTime = forms.IntegerField()
    CustomerSwitchTime = forms.FloatField()

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

Main/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class SimulationPage(TemplateView):
    template_name = 'simulation.html'

MyWeb/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from .forms import PostForm
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt, mpld3
#import seaborn as sns
#import matplotlib.animation as animation
from mpl_toolkits.axisartist.axislines import Subplot
import os
from decimal import Decimal



class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class ResultPage(TemplateView):
    template_name = 'result.html'


class SimulationPage(TemplateView):
    template_name = 'new_simulation.html'
    NumOfCusts = "1"


    def get(self, request):
        form = PostForm()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            Sum_of_Var1_and_Var2 = form.cleaned_data['Min_serving_time_of_the_receptionits']+form.cleaned_data['Max_serving_time_of_the_receptionits']
            NumOfCusts = form.cleaned_data['Number_of_Costomers']
            NumOfRecs = form.cleaned_data['Number_of_Receptionists']
            MinServTime = form.cleaned_data['Min_serving_time_of_the_receptionits']
            MaxServTime = form.cleaned_data['Max_serving_time_of_the_receptionits']
            MinArvTime = form.cleaned_data['MinCustonArrivalTime']
            MaxArvTime = form.cleaned_data['MaxCustonArrivalTime']
            CustSwitchT = form.cleaned_data['CustomerSwitchTime']

        intNumOfCusts = int(NumOfCusts)
        a=np.random.rand(intNumOfCusts)

        b=np.array(range(intNumOfCusts), int)
        L=np.array(range(intNumOfCusts), int)
        q=np.array(range(intNumOfCusts), int)

        def fu(self, request):
            for i in b:
                b[i]=np.random.randint(MinServTime,MaxServTime)
        fu(self, request)

        c=(a+b)/NumOfRecs
        a2=np.random.rand(intNumOfCusts)
        b2=np.array(range(intNumOfCusts), int)

        def fu2(self, request):
            for i in b2:
                b2[i]=np.random.randint(MinArvTime,MaxArvTime)
        fu2(self, request)
        e=a2+b2

        f=np.array(range(intNumOfCusts), float)

        def fu3(self, request):
            f[0]=e[0]
            i=1
            while 0<i<intNumOfCusts:
                f[i]=e[i]+f[i-1]
                i+=1
        fu3(self, request)

        T=CustSwitchT
        g=np.array(range(intNumOfCusts), float)

        def fu4(self, request):
            g[0]=c[0]+e[0]
            i=1
            while 0<i<intNumOfCusts:
                if g[i-1]>e[i]+e[i-1]:
                    g[i]=T+g[i-1]+c[i]

                else:
                    T+e[i]+e[i-1]+c[i]

                i+=1


        fu4(self,request)

        h=np.array(range(intNumOfCusts), float)

        def fu5(self, request):
            h[0]=0
            i=1
            while 0<i<intNumOfCusts:
                h[i]=g[i-1]-f[i]-T
                i+=1
        fu5(self, request)

        z=np.array(range(intNumOfCusts), float)

        def fu6(self, request):
            z[0]=0
            i=1
            while 0<i<intNumOfCusts:
                if h[i]>0:
                    z[i]=h[i]
                else:
                    z[i]=0
                i+=1
        fu6(self, request)


        Label=intNumOfCusts+1
        DAT=range(1,Label,1)
        q=h.tolist()
        TEST = pd.Series(q, DAT)
        #TEST.plot.bar()
        fig, ax = plt.subplots()
        ax.plot(DAT, q)
        ax.set(xlabel='Customer numaration sorted by arrival time', ylabel='Waiting time of a customer (Minutes)',
       title='Your Result')
        RES=mpld3.fig_to_html(fig)
        ax.grid()
        fig.savefig('D:\Model\MyWeb\static\Main\images\myplot.png')



        df=pd.DataFrame(data=q,index=DAT,columns=['The waiting line of each customer'])




        xyz=np.array(range(intNumOfCusts), float)
        def fu7(self, request):
            xyz[0]=0
            i=1
            while 0<i<intNumOfCusts:
                if z[i]>0:
                    xyz[i]=round(Decimal(z[i]), 2)
                else:
                    xyz[i]=0
                i+=1
        fu7(self, request)


        args = {'form':form, 'Sum_of_Var1_and_Var2':Sum_of_Var1_and_Var2,
        'intNumOfCusts':intNumOfCusts, 'a':a, 'b':b, 'a2':a2, 'b2':b2, 'g':g, 'c':c,
        'NumOfCusts':NumOfCusts, 'MinServTime':MinServTime, 'MaxServTime':MaxServTime,
        'h':h, 'e':e, 'f':f, 'z':z, 'L':L, 'xyz':xyz,
        'TEST':TEST, 'DAT':DAT, 'Label':Label, 'q':q, 'df':df, 'fig':fig, 'RES':RES,}
        return render(request, self.template_name, args)



class HomePage(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

#class SimulationPage(TemplateView):
    #template_name = 'new_simulation.html'

accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Business Modeling</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

              <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}

                      <li><a href="{% url 'home' %}">Home</a></li>
                      <li><a href="#">About</a></li>
                      <li><a href="#">Contact</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
              {% else %}
                      <li><a href="{% url 'home' %}">Home</a></li>
                      <li><a href="#">About</a></li>
                      <li><a href="#">Contact</a></li>
                      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
              {% endif %}
              </ul>

    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "Main/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Business Modeling Web Site!</h1>
    <video width="720" height="480" controls style="margin-left: auto; display: block; margin-right: auto;">
        <source src="movie.mp4" type="video/mp4">
        <source src="movie.ogg" type="video/ogg">
    Your browser does not support the video tag.
    </video>




{% endblock %}

templates/new_simulation.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


      <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="save btn btn-default">Simulate</button>
      </form>




{% autoescape off %}
<div>{{ RES }}</div>
{% endautoescape %}

<h2>Waiting time of the customers in the line sorted by arrival time</h2>
<p></p>
<ol>

            {% for i in xyz %}
              <li>{{ i }} minutes</li>
            {% endfor %}
</ol>



{% endblock %}

templates/result.html
{% extends "base.html" %}

{% block content %}


        <h1 class='posttitle loader'>{{ post.User }}</h1>



      <p class='postcontent' >{{ post.num3|safe|linebreaksbr }}</p>

      <p>This is your result: {{ Numsum.num3 }}</p>

{% endblock %}

templates/simulation.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Business Modeling Web Site!</h1>

    <h2>you can start your simulation here</h2>


    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>




{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'simulation' %}">Click here to start Business Simulation!</a></h2>


</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}